version: '3'
services:
  broker-service:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/code
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: